name: user_app
description: "TR Store User App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  sqflite: ^2.3.2
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  http: ^1.2.0
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: lato
      fonts:
        - asset: assets/font/Lato-Light.ttf
          weight: 100
        - asset: assets/font/Lato-Regular.ttf
          weight: 500
        - asset: assets/font/Lato-Bold.ttf
          weight: 700
